services:
  radiotelegram:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radiotelegram
    restart: unless-stopped
    
    # Environment variables
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TELEGRAM_TOPIC_ID=${TELEGRAM_TOPIC_ID}
      - AUDIO_DEVICE=${AUDIO_DEVICE:-hw:1,0}
    
    # Load environment from .env file
    env_file:
      - .env
    
    # Audio device access
    devices:
      - /dev/snd:/dev/snd  # ALSA sound devices
      - /dev/bus/usb:/dev/bus/usb  # USB devices
    
    # Volume mounts for ALSA configuration
    volumes:
      - /usr/share/alsa:/usr/share/alsa:ro
      - /etc/asound.conf:/etc/asound.conf:ro
    
    # Privileged mode for full hardware access
    privileged: true
    
    cap_add:
      - SYS_NICE  # For audio priority
      - SYS_ADMIN  # For device management
