services:
  radiotelegram:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radiotelegram
    restart: unless-stopped
    
    # Environment variables
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TELEGRAM_TOPIC_ID=${TELEGRAM_TOPIC_ID}
      - AUDIO_DEVICE=${AUDIO_DEVICE:-pipewire}
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - XDG_RUNTIME_DIR=/run/user/1000
    
    # Load environment from .env file
    env_file:
      - .env
    
    # Audio device access
    # devices:
    #   - /dev/snd:/dev/snd
    
    # Volume mounts
    volumes:
      # PulseAudio/PipeWire socket access
      - /run/user/1000/pulse:/run/user/1000/pulse:rw
      - /run/user/1000/pipewire-0:/run/user/1000/pipewire-0:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    
    # Network mode for audio access
    network_mode: host
    
    cap_add:
      - SYS_NICE  # For audio priority
    
    user: "1000:1000"
