services:
  radiotelegram:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radiotelegram
    restart: unless-stopped
    
    # Environment variables
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TELEGRAM_TOPIC_ID=${TELEGRAM_TOPIC_ID}
      - AUDIO_DEVICE=${AUDIO_DEVICE:-pulse}
    
    # Load environment from .env file
    env_file:
      - .env
    
    # Audio device access
    devices:
      - /dev/snd:/dev/snd
    
    # Volume mounts
    volumes:
      # Audio socket (try PulseAudio first, then PipeWire)
      - /run/user/1000/pulse:/run/user/1000/pulse
    
    # Network mode for audio access
    network_mode: host
    
    # Privileged mode might be needed for audio device access
    # privileged: true
    
    # Alternative: specific capabilities for audio
    cap_add:
      - SYS_NICE  # For audio priority
    
    # User mapping (match host user for audio access)
    user: "1000:1000"
